---
- name: Basic Cisco Router Configuration
  hosts: router
  gather_facts: no
  connection: network_cli
  vars:
    console_password: "cisco"
    enable_secret: "class"

  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname R1

    - name: Configure console line
      ios_config:
        lines:
          - line console 0
          - password {{ console_password }}
          - login

    - name: Set enable secret
      ios_config:
        lines:
          - enable secret {{ enable_secret }}

    - name: Configure password encryption
      ios_config:
        lines:
          - service password-encryption

    - name: Set banner
      ios_config:
        lines:
          - banner motd "Unauthorized access is prohibited!"

    - name: Save configuration
      ios_config:
        save_when: always



